var dir_61b11efe21cdabcae0da887f334f2987 =
[
    [ "C-interface", "dir_51b49fdf960fa9fa2ba5905a68a6a1cb.html", "dir_51b49fdf960fa9fa2ba5905a68a6a1cb" ],
    [ "APIDef.h", "_a_p_i_def_8h.html", "_a_p_i_def_8h" ],
    [ "BaseManager.h", "_base_manager_8h.html", "_base_manager_8h" ],
    [ "Configuration.h", "_configuration_8h.html", "_configuration_8h" ],
    [ "ConsumptionPeriod.h", "_consumption_period_8h.html", "_consumption_period_8h" ],
    [ "CryptoProvider.h", "_crypto_provider_8h.html", "_crypto_provider_8h" ],
    [ "Customer.h", "_customer_8h.html", "_customer_8h" ],
    [ "CustomField.h", "_custom_field_8h.html", "_custom_field_8h" ],
    [ "DeviceVariable.h", "_device_variable_8h.html", "_device_variable_8h" ],
    [ "EncryptString.h", "_encrypt_string_8h.html", "_encrypt_string_8h" ],
    [ "Exceptions.h", "_exceptions_8h.html", "_exceptions_8h" ],
    [ "ExtendedOptions.h", "_extended_options_8h.html", "_extended_options_8h" ],
    [ "FloatingClient.h", "_floating_client_8h.html", "_floating_client_8h" ],
    [ "FloatingServerInfo.h", "_floating_server_info_8h.html", "_floating_server_info_8h" ],
    [ "InstallationFile.h", "_installation_file_8h.html", "_installation_file_8h" ],
    [ "License.h", "_license_8h.html", "_license_8h" ],
    [ "LicenseFeature.h", "_license_feature_8h.html", "_license_feature_8h" ],
    [ "LicenseFileStorage.h", "_license_file_storage_8h.html", "_license_file_storage_8h" ],
    [ "LicenseHandler.h", "_license_handler_8h.html", "_license_handler_8h" ],
    [ "LicenseID.h", "_license_i_d_8h.html", "_license_i_d_8h" ],
    [ "LicenseManager.h", "_license_manager_8h.html", "_license_manager_8h" ],
    [ "LicenseMemoryStorage.h", "_license_memory_storage_8h.html", "_license_memory_storage_8h" ],
    [ "LicenseStorage.h", "_license_storage_8h.html", "_license_storage_8h" ],
    [ "LicenseType.h", "_license_type_8h.html", "_license_type_8h" ],
    [ "LicenseUser.h", "_license_user_8h.html", "_license_user_8h" ],
    [ "PODTypes.h", "_p_o_d_types_8h.html", "_p_o_d_types_8h" ],
    [ "ProductDetails.h", "_product_details_8h.html", "_product_details_8h" ],
    [ "Version.h", "_version_8h.html", "_version_8h" ]
];