name: Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-mac:
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Build Plugin Mac AU & VST3
        run: |
          cd Builds/MacOSX/CodaBuilds
          xcodebuild -project "Coda.xcodeproj" -scheme "Coda - All" -configuration Release

      - name: Sign Mac Builds
        env:
          HASH_OF_DEVELOPER_ID_APPLICATION: ${{ secrets.HASH_OF_DEVELOPER_ID_APPLICATION }}
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH $(security list-keychain -d user | sed s/\"//g)
          security list-keychains -s $KEYCHAIN_PATH

          # verify certificate import
          security find-identity -p codesigning -v

          # set key partition list
          security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # sign components using full identity string
          FULL_IDENTITY_STRING="Developer ID Application: Kyle Stemberger (8SY577X9L5)"
          cd Builds/MacOSX
          ls
          codesign --deep --force --options=runtime --sign "$FULL_IDENTITY_STRING" --timestamp CODA/Builds/MacOSX/CodaBuilds/build/Release/CodaExternalDSP.component || exit 1
          codesign --deep --force --options=runtime --sign "$FULL_IDENTITY_STRING" --timestamp CODA/Builds/MacOSX/CodaBuilds/build/Release/CodaExternalDSP.vst3 || exit 1

      - name: Create Installer Mac AU
        run: |
          pkgbuild --root CODA/Builds/MacOSX/CodaBuilds/build/Release/ \
          --identifier com.HavenAudio.CODA \
          --install-location CODA/Builds/MacOSX/CodaBuilds/build/Release/ \
          --version "1.0.3" \
          CodaExternalDSP-au.pkg

      - name: Create Installer Mac VST3
        run: |
          pkgbuild --root CODA/Builds/MacOSX/CodaBuilds/build/Release/ \
          --identifier com.HavenAudio.CODA \
          --install-location CODA/Builds/MacOSX/CodaBuilds/build/Release/ \
          --version "1.0.0" \
          CodaExternalDSP-vst3.pkg

      - name: Upload AU Installer
        uses: actions/upload-artifact@v3
        with:
          name: Mac-Installer-AU
          path: CodaExternalDSP-au.pkg

      - name: Upload VST3 Installer
        uses: actions/upload-artifact@v3
        with:
          name: Mac-Installer-VST3
          path: CodaExternalDSP-vst3.pkg

